version: '3.9'
services:
  portalservice:
    image: kds.inveniacorp.com/dev/portal-service/portal-service:latest
    networks:
      - msa
    ports:
      - "8012:8012"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: "8012"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
      KEYCLOAK_URI: "http://100.100.15.82:8080/auth" # 호스트 주소
      KEYCLOAK_REALM: "service"
      CONFIGSERVER_URI: "http://configserver:8888"
networks:
  msa:
    external: true
    name: msa
