name: Portal Service Build Action

on: [ push, pull_request ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Login Docker
        if: github.event_name != 'pull_request'
        uses: actions/login-action@v1.10.0
        with:
          registry: kds.inveniacorp.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jib
